# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubActionsToolbox < Formula
  desc "CLI toolbox for GitHub Actions"
  homepage "https://github.com/rlespinasse/github-actions-toolbox"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v1.0.0/github-actions-toolbox_1.0.0_darwin_amd64.tar.gz"
      sha256 "82573b227e77b13e9dc1e13c4e00a345008a2cf286565db4b5a0cdc71ee3b7de"

      define_method(:install) do
        bin.install "ghat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v1.0.0/github-actions-toolbox_1.0.0_darwin_arm64.tar.gz"
      sha256 "d66ede08f43b906ff7a73eccef82c9dff18580193dc749e940b66d69a9f25a95"

      define_method(:install) do
        bin.install "ghat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v1.0.0/github-actions-toolbox_1.0.0_linux_amd64.tar.gz"
      sha256 "923cb06e4fee12267461f827dd7b54f5cb42ff342acc7830d49baf14e8489404"
      define_method(:install) do
        bin.install "ghat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v1.0.0/github-actions-toolbox_1.0.0_linux_arm64.tar.gz"
      sha256 "239eb64d70c19f071cb48f4d08dad928fe9c0b5f86fc627767af1f33b25c0b28"
      define_method(:install) do
        bin.install "ghat"
      end
    end
  end
end
