# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-actions-toolbox" do
  name "github-actions-toolbox"
  desc "CLI toolbox for GitHub Actions"
  homepage "https://github.com/rlespinasse/github-actions-toolbox"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghat"

  on_macos do
    on_intel do
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v#{version}/github-actions-toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "022d7eab0bb1a474d24ae33dd4a0f9b811b22654d22c024d26ca8edf46715830"
    end
    on_arm do
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v#{version}/github-actions-toolbox_#{version}_darwin_arm64.tar.gz"
      sha256 "6ee46df16d4da3bbc60a293fdc4ef79b72344b96e6f9f90c700462b4d2127b53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v#{version}/github-actions-toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "9a7436fb526affad6998bc5d04cafff2e6fe8c70207c2169c62329230660398e"
    end
    on_arm do
      url "https://github.com/rlespinasse/github-actions-toolbox/releases/download/v#{version}/github-actions-toolbox_#{version}_linux_arm64.tar.gz"
      sha256 "f699dcfbce4ae73a45d5e59bf99ada1ea100cbecd7f731539a95b050f1c5c48f"
    end
  end

  # No zap stanza required
end
