# This file was generated by GoReleaser. DO NOT EDIT.
cask "ihatt" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "3e4e0b1a918f28f5adfa8f59b5f3f6caccb0f3665c940393491f0f2aecf62138"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "59f8f0f48b242bac47e374491c0b437b3fba0a94d6f582fb28d55d09c7d7ac30"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "453a6e78e67cff022f5d01b1d1b4d3232fa9de6692fc3bbb189733c2af6fd635"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee91f6a732fcc920adabbdf43a90f5f85f0a1d42d8b10e3aa779c5d2ddca2034"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ihatt"
  desc "CLI/TUI temporal knowledge base over local git repos"
  homepage "https://github.com/rlespinasse/ihatt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ihatt"

  # No zap stanza required

end
