# This file was generated by GoReleaser. DO NOT EDIT.
cask "ihatt" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "9ced93270445d2abea9369978e45b8f6bea7cd8cc9676f694ec1d8d2645900ae"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f528e34cfc58fda6ac0ad4a9d88d37d10e311518e479124c0088489fcd3c674"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2511c1be9f6ed5d6485e4f7c2674c3afe4429419c9b4d03c8f942c06ccaa9ae0"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9a5140e4133ee6467496286b4e8bd41ccce05e3675c6fdfc0d8d9218d22ce1d"
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ihatt"
  desc "CLI/TUI temporal knowledge base over local git repos"
  homepage "https://github.com/rlespinasse/ihatt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ihatt"

  # No zap stanza required

  caveats <<~EOS
    macOS Gatekeeper notice: this binary is signed but not notarized by Apple.
    On first run, macOS may block it. If so, allow it via:
      System Settings > Privacy & Security > "Allow Anyway"
    or run:
      xattr -d com.apple.quarantine $(brew --prefix)/bin/ihatt
  EOS
end
