# This file was generated by GoReleaser. DO NOT EDIT.
cask "ihatt" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_darwin_amd64.tar.gz"
      sha256 "502374ffff01a306f988e6e73d4c647718ecb85e0201686e868df0f9ef59fa89"
    end
    on_arm do
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_darwin_arm64.tar.gz"
      sha256 "697cf4e04702e6a3c4d41d7f3ad3de76018e40411ac40e06a8b01cab7fce5c0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_linux_amd64.tar.gz"
      sha256 "865e416fd3595bceeaac256b4244e391b51800487401554effa7c03ccd0cc04d"
    end
    on_arm do
      url "https://github.com/rlespinasse/ihatt/releases/download/v#{version}/ihatt_#{version}_linux_arm64.tar.gz"
      sha256 "cda642b35fb7d48200e4d8276a6e5e9d81ef02b80442af8c4959992d67ea4308"
    end
  end

  name "ihatt"
  desc "CLI/TUI temporal knowledge base over local git repos"
  homepage "https://github.com/rlespinasse/ihatt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ihatt"

  # No zap stanza required

end
